STATES = { # translate trac terminology to GH issues
		'new': 'open',
		'assigned': 'open',
		'reopened': 'open',
		'closed': 'closed',
		}

MILESTONES = { # assign temporary, unique ID for each milestone
		'Future': 0,
		'2008.0': 1,
		'2008.1': 2,
		'2009.0': 3,
		'2009.1': 4,
		'2009.2': 5,
		'2010.1': 6,
		'2011.1': 7,
		'2011.2': 8,
		'GSoC 2011: Deadline': 9,
		'2011.3':10,
		'Website migration': 11,
		'2012.1':12,
		'2012.2':13,
		'2012.3':14,
		'Organization': 15,
		}

# map reporter and comment author names to either GH account {'login': username}
# or email address {'email': email@ddress) (only if GH account exists for that mail)
USERNAMES = {
		'Andre' : {'login' : 'AndreR'},
		'christoph' : {'login' : 'siccegge'}, # christoph_debian
		'court-jus' : {'login' : 'court-jus'},
		'enno4uh' : {'login' : 'enno4uh'},
		'eoc' : {'login' : 'ChrisOelmueller'},
		'GreyGhost' : {'login' : 'GreyGhost'},
		'Grickit' : {'login' : 'grickit'},
		'gscai' : {'login' : 'otinn'},
		'H0ff1' : {'login' : 'hoffi'},
		'kaschte' : {'login' : 'kaschte'},
		'ketheriel' : {'login' : 'ketheriel'},
		'kili' : {'login' : 'stubb'},
		'kinshuksunil' : {'login' : 'kinshuksunil'},
		'Kiryx' : {'login' : 'kiryx'},
		'LinuxDonald' : {'login' : 'LinuxDonald'},
		'manuel' : {'login' : 'manuelm'},
		'MasterofJOKers' : {'login' : 'MasterofJOKers'},
		'mbivol' : {'login' : 'mihaibivol'},
		'MSSSSM' : {'login' : 'mssssm'},
		'mtfk' : {'login' : 'mitfik'},
		'mvBarracuda' : {'login' : 'mvbarracuda'},
		'nightraven' : {'login' : 'tschroefel'},
		'Nightraven' : {'login' : 'tschroefel'},
		'nihathrael' : {'login' : 'nihathrael'},
		'prock' : {'login' : 'prock-fife'},
		'qubodup' : {'login' : 'qubodup'},
		'RainCT' : {'login' : 'RainCT'},
		'Sharkash' : {'login' : 'Vivek-sagar'},
		'sidi' : {'login' : 'sids-aquarius'},
		'spq' : {'login' : 'spq'},
		'squiddy' : {'login' : 'squiddy'},
		'totycro' : {'login' : 'totycro'},
		'TunnelWicht' : {'login' : 'TunnelWicht'},
		'wentam' : {'login' : 'wentam'},
		}

UNKNOWN = {
		'AyCe' : {'login' : ''},
		'dauerflucher' : {'login' : ''},
		'Manthus' : {'login' : ''},
		'terwarf' : {'login' : ''},
		'tuempl' : {'login' : ''},
		'Juarrox' : {'login' : ''},
		'Iankap99' : {'login' : ''},
		'raymond' : {'login' : ''},
		'dario' : {'login' : ''},
		'IwfY' : {'login' : ''},
		'pkerling' : {'login' : ''},
		'lynxis' : {'login' : ''},
		'yonibear' : {'login' : ''},
		'RealNitro' : {'login' : ''},
		'Psycojoker' : {'login' : ''},
		'patty' : {'login' : ''},
		'dreimer' : {'login' : ''},
		'lynxis_' : {'login' : ''},
		'scaabi' : {'login' : ''},
		'Soeb' : {'login' : ''},
		'janus' : {'login' : ''},
		'Amfidiusz' : {'login' : ''},
		'Quassy' : {'login' : ''},
		'Yeya' : {'login' : ''},
		'Crendgrim' : {'login' : ''},
		'Fabio Pedretti' : {'login' : ''},
		'deathmaster9' : {'login' : ''},
		'Torv' : {'login' : ''},
		'josch' : {'login' : ''},
		'Emperor2k3' : {'login' : ''},
		'seblabel' : {'login' : ''},
		'ronnie_c' : {'login' : ''},
		'Foaly' : {'login' : ''},
		'RM87' : {'login' : ''},
		'MadMonk' : {'login' : ''},
		'LiveWire' : {'login' : ''},
		'Mastaxlokks' : {'login' : ''},
		'Nikolai' : {'login' : ''},
		'o01eg' : {'login' : ''},
		'MoXe' : {'login' : ''},
		}
